# -*- coding: utf-8 -*-
"""Handwritten Alphabets (A to Z) Recognition using ANN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E_FZJfzaAV90QClXzZqgNxsJm9r44vDK

Install package
"""

!pip install tensorflow-datasets

"""Import libraries"""

import tensorflow_datasets as tfds
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.utils import to_categorical

"""Load complete EMNIST Letters dataset"""

dataset = tfds.load(
    'emnist/letters',
    split='train',
    as_supervised=True
)

X=[]
y=[]

for image,label in tfds.as_numpy(dataset):
    X.append(image)
    y.append(label)

X=np.array(X)
y=np.array(y)

print("Image shape:",X.shape)
print("Label shape:",y.shape)
print("Classes:",np.unique(y))

"""Fix EMNIST orientation"""

X = np.transpose(X,(0,2,1,3))
X = np.flip(X,axis=2)

plt.figure(figsize=(10,5))

for i in range(10):
    plt.subplot(2,5,i+1)
    plt.imshow(X[i],cmap='gray')
    plt.title(chr(y[i]+64))
    plt.axis("off")

plt.show()

"""Preprocessing"""

X = X.reshape(-1,784)
X = X/255.0

# Labels: 1–26 → 0–25
y = y-1

# Split data
X_train,X_test,y_train,y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# One hot encoding
y_train=to_categorical(y_train,26)
y_test=to_categorical(y_test,26)

print(X_train.shape)
print(X_test.shape)

"""Create ANN model"""

model=Sequential()

model.add(Dense(
    512,
    activation='relu',
    input_shape=(784,)
))

model.add(Dropout(0.3))

model.add(Dense(
    256,
    activation='relu'
))

model.add(Dropout(0.3))

model.add(Dense(
    128,
    activation='relu'
))

model.add(Dropout(0.3))

model.add(Dense(
    26,
    activation='softmax'
))

"""Dense(64) → may learn fewer features
Dense(128) → moderate learning
Dense(256) → stronger feature learning
Dense(1024) → may become unnecessarily complex

=============

A **Dense layer** connects every neuron from the previous layer to every neuron in the next layer.
It helps the model learn patterns and relationships from the input data.
The number inside Dense() represents the number of neurons.

============

**Dropout is used to reduce overfitting in a neural network**

Simple explanation:

Imagine 100 students studying together. If the same students always answer every question, some students may become over-dependent on others.

Dropout works like this:

During training, it randomly turns off (drops) some neurons temporarily.
Example: Dropout(0.5) → randomly ignores 50% of neurons in each training step.
The network is forced to learn from different neuron combinations.
This prevents the model from memorizing the training data and helps it generalize better for new data.

================

**Dense(256) → creates 256 neurons**
--------------------------------------------------------

**Dropout(0.3) → randomly disables 30% of neurons during training**

Benefits:
✅ Reduces overfitting
✅ Improves generalization
✅ Makes predictions more reliable on unseen data
✅ Can improve accuracy

Compile model
"""

model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

model.summary()

"""Train model"""

history=model.fit(
    X_train,
    y_train,
    epochs=10,
    batch_size=128,
    validation_data=(X_test,y_test)
)

"""Prediction"""

y_pred=model.predict(X_test)

y_pred_classes=np.argmax(
    y_pred,
    axis=1
)

y_true_classes=np.argmax(
    y_test,
    axis=1
)

"""Classification Report"""

alphabet_labels=[
    chr(i)
    for i in range(65,91)
]

print(
    classification_report(
        y_true_classes,
        y_pred_classes,
        target_names=alphabet_labels
    )
)

"""Confusion Matrix"""

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

# Convert one-hot encoded labels back to normal labels
y_test_letter_eval = y_true_classes

# Predict test images
y_predicts = y_pred_classes

# Confusion Matrix
con_mat = confusion_matrix(y_test_letter_eval, y_predicts)

# Alphabet labels
labels = alphabet_labels

plt.figure(figsize=(15,15))

sns.heatmap(
    con_mat, # Removed slicing [1:,1:] to include all classes (A-Z)
    annot=True,
    fmt='d',
    cmap='gray',
    xticklabels=labels,
    yticklabels=labels
)

plt.title(
    "Confusion Matrix for Alphabet Recognition",
    fontweight='bold',
    fontsize=15
)

plt.xlabel("Predicted Alphabet")
plt.ylabel("Actual Alphabet")

plt.show()

print(history.history.keys())

# summarize history for accuracy
plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])
plt.title('model accuracy')
plt.ylabel('accuracy')
plt.xlabel('epoch')
plt.legend(['train', 'test'], loc='best')
plt.show()

plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title('model loss')
plt.ylabel('loss')
plt.xlabel('epoch')
plt.legend(['train', 'test'], loc='best')
plt.show()

import numpy as np
import matplotlib.pyplot as plt

# Find alphabet A (A is 0-indexed as 0)
i = np.where(y_true_classes == 0)[0][0]

# Predict single image
y_predict_single = model.predict(X_test[[i]])
y_predict_single = np.argmax(y_predict_single, axis=1)

# Convert labels to alphabets
actual = alphabet_labels[y_true_classes[i]]
predicted = alphabet_labels[y_predict_single[0]]

# Display image
plt.imshow(X_test[i].reshape(28,28), cmap='gray')

plt.xlabel(
    "Actual:{} Pred:{}".format(
        actual,
        predicted
    )
)

plt.show()

import numpy as np
import matplotlib.pyplot as plt

# Find alphabet E (E is 0-indexed as 0)
i = np.where(y_true_classes == 4)[0][0]

# Predict single image
y_predict_single = model.predict(X_test[[i]])
y_predict_single = np.argmax(y_predict_single, axis=1)

# Convert labels to alphabets
actual = alphabet_labels[y_true_classes[i]]
predicted = alphabet_labels[y_predict_single[0]]

# Display image
plt.imshow(X_test[i].reshape(28,28), cmap='gray')

plt.xlabel(
    "Actual:{} Pred:{}".format(
        actual,
        predicted
    )
)

plt.show()

import numpy as np
import matplotlib.pyplot as plt

# Find alphabet W (W is 0-indexed as 0)
i = np.where(y_true_classes == 22)[0][0]

# Predict single image
y_predict_single = model.predict(X_test[[i]])
y_predict_single = np.argmax(y_predict_single, axis=1)

# Convert labels to alphabets
actual = alphabet_labels[y_true_classes[i]]
predicted = alphabet_labels[y_predict_single[0]]

# Display image
plt.imshow(X_test[i].reshape(28,28), cmap='gray')

plt.xlabel(
    "Actual:{} Pred:{}".format(
        actual,
        predicted
    )
)

plt.show()

"""| Alphabet | Index |
| -------- | ----- |
| A        | 0     |
| B        | 1     |
| C        | 2     |
| D        | 3     |
| E        | 4     |
| F        | 5     |
| G        | 6     |
| H        | 7     |
| I        | 8     |
| J        | 9     |
| K        | 10    |
| L        | 11    |
| M        | 12    |
| N        | 13    |
| O        | 14    |
| P        | 15    |
| Q        | 16    |
| R        | 17    |
| S        | 18    |
| T        | 19    |
| U        | 20    |
| V        | 21    |
| W        | 22    |
| X        | 23    |
| Y        | 24    |
| Z        | 25    |

Confusion Matrix:

The confusion matrix shows that most values are concentrated on the diagonal, indicating correct predictions. **Alphabet O showed a high correct prediction value (663)**, meaning the model learned that class well.

===================

Classification Report:

The classification report shows that the model achieved an **overall accuracy of 91%.** Alphabets M, O, W, X, and Z showed strong performance with high scores.
"""